name: Run char_check.py

on:
  pull_request:
    branches: [main]

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    env:
      SCRIPT_PATH: source_files/char_check.py
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run char_check.py script
      run: python $SCRIPT_PATH
