name: Packer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run package script
      run: python source_files/packer.py

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-artifact
        path: patch-out
